### ISSUE TITLE
Build with NDK r15

### ISSUE THREAD

**Issue by contendar** [Bilibili/ijkplayer#3444]
When I build using NDK version 15.0.4075724 it compiles fine but I get following error while linking

> libavformat/hls.c:773: error: undefined reference to 'atof'
> libavformat/hlsproto.c:149: error: undefined reference to 'atof'
> libavutil/file.c:85: error: undefined reference to 'mmap64'
> libavutil/log.c:188: error: undefined reference to 'stderr'
> libavutil/log.c:362: error: undefined reference to 'stderr'
> libavutil/log.c:362: error: undefined reference to 'stderr'

But when I use NDK r10e then it works fine, Is there any thing I can do to make it compile with NDK r15?
I am also attaching my terminal output

[Terminal Saved Output.txt](https://github.com/Bilibili/ijkplayer/files/1203194/Terminal.Saved.Output.txt)
Thank You

**Comment by AlanJaver** [comment]
r14 is ok

**Comment by afterxiong** [comment]
ndk-r14b  ok

**Comment by don11995** [comment]
To build player (ffmpeg and openssl) with NDK r15 You need to use `--deprecated-headers` while creating standalone toolchain.
To do so You need to use create toolchain command as below:
```
$ANDROID_NDK/build/tools/make_standalone_toolchain.py \
                --deprecated-headers \
		--arch x86 \
                --api 16 \
                --install-dir $TOOLCHAIN_DIR
```

**Comment by neevek** [comment]
> To build player (ffmpeg and openssl) with NDK r15 You need to use `--deprecated-headers` while creating standalone toolchain.
> To do so You need to use create toolchain command as below:
> 
> ```
> $ANDROID_NDK/build/tools/make_standalone_toolchain.py \
>                 --deprecated-headers \
> 		--arch x86 \
>                 --api 16 \
>                 --install-dir $TOOLCHAIN_DIR
> ```
> Some additional info: [NDK r15 unified headers](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md)

make_standalone_toolchain.py: error: unrecognized arguments: --deprecated-headers

The NDK version I am using is 17.1.4828580
