### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by SamPeng87** [Bilibili/ijkplayer#3378]
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=/Users/sampeng/export/android-sdk-macosx/ndk-bundle
IJK_NDK_REL=15.0.4075724
NDKr15.0.4075724 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.

是不支持15么。。。

**Comment by SamPeng87** [comment]
找到问题了。。15不支持api 9的编译了。。改成14完事。。。不需要支持4.1以下系统

**Comment by SamPeng87** [comment]
还是有问题
libavformat/hls.c:773: error: undefined reference to 'atof'

**Comment by SamPeng87** [comment]
发现编译ffmpeg本身是过去了。但到这一步的时候，出错
    `
$CC -lm -lz -shared --sysroot=$FF_SYSROOT -Wl,--no-undefined -Wl,-z,noexecstack $FF_EXTRA_LDFLAGS \
    -Wl,-soname,libijkffmpeg.so \
    $FF_C_OBJ_FILES \
    $FF_ASM_OBJ_FILES \
    $FF_DEP_LIBS \
    -o $FF_PREFIX/libijkffmpeg.so`
echo "error cc"

**Comment by BIGMONK** [comment]
我的14也报错
build on MINGW64_NT-10.0 x86_64
ANDROID_NDK=F:\djf\Android\sdk\ndk-bundle
IJK_NDK_REL=14.1.3816874
NDKr14.1.3816874 detected
HOST_OS=windows
HOST_EXE=.exe
HOST_ARCH=x86_64
HOST_TAG=windows-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.

**Comment by andy-zhangtao** [comment]
Me too. 从shell脚本中找出下面出错命令，单独执行

```
$ANDROID_NDK/build/tools/make-standalone-toolchain.sh
```

报错显示不支持14以下的api。 改成14以后，也出现上面的错误

```
libavformat/hls.c:773: error: undefined reference to 'atof'
libavformat/hlsproto.c:149: error: undefined reference to 'atof'
libavutil/file.c:85: error: undefined reference to 'mmap64'
libavutil/log.c:188: error: undefined reference to 'stderr'
libavutil/log.c:362: error: undefined reference to 'stderr'
libavutil/log.c:362: error: undefined reference to 'stderr'
collect2: error: ld returned 1 exit status
```

**Comment by andy-zhangtao** [comment]
找到问题根源了， android从ndk10开始，将一些C函数变成了内联函数。例如atof：

```
static __inline__ double atof(const char *nptr)
{
    return (strtod(nptr, NULL));
}
```

函数名称变成了strtod。 所以在10之后，就会变成找不到此函数声明。

目前ijkplayer应该不支持ndk 15.  要么使用其它版本，要么其它其它框架。 别无他法了....

**Comment by isuker** [comment]
libavformat/hls.c:773: error: undefined reference to 'atof'
libavformat/hlsproto.c:149: error: undefined reference to 'atof'

replace
//            duration   = atof(ptr) * AV_TIME_BASE;  
            duration   = strtod(ptr, NULL) * AV_TIME_BASE;

**Comment by kingthy** [comment]
apt-get install python
安装python后再执行编译即可解决ERROR: Failed to create toolchain.问题

**Comment by zishang520** [comment]
@kingthy 似乎这样可以了

**Comment by dourgulf** [comment]
把android API改到21之后，atof和mmap64的链接没问题了，stderr的还是报错。

**Comment by fukemy** [comment]
install python not working to me, still got error (NDK 17 :( )

```
THG:contrib thehe$ ./compile-ffmpeg.sh all 
====================
[*] check archs
====================
FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64

====================
[*] check env armv5
====================
FF_ARCH=armv5
FF_BUILD_OPT=

--------------------
[*] make NDK standalone toolchain
--------------------
build on Darwin x86_64
ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
IJK_NDK_REL=17.1.4828580
NDKr17.1.4828580 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.
THG:contrib thehe$ 

```

**Comment by WenqiangXie** [comment]
> install python not working to me, still got error (NDK 17 :( )
> 
> ```
> THG:contrib thehe$ ./compile-ffmpeg.sh all 
> ====================
> [*] check archs
> ====================
> FF_ALL_ARCHS = armv5 armv7a arm64 x86 x86_64
> FF_ACT_ARCHS = armv5 armv7a arm64 x86 x86_64
> 
> ====================
> [*] check env armv5
> ====================
> FF_ARCH=armv5
> FF_BUILD_OPT=
> 
> --------------------
> [*] make NDK standalone toolchain
> --------------------
> build on Darwin x86_64
> ANDROID_NDK=/Users/thehe/Library/Android/sdk/ndk-bundle
> IJK_NDK_REL=17.1.4828580
> NDKr17.1.4828580 detected
> HOST_OS=darwin
> HOST_EXE=
> HOST_ARCH=x86_64
> HOST_TAG=darwin-x86_64
> HOST_NUM_CPUS=8
> BUILD_NUM_CPUS=16
> Auto-config: --arch=arm
> ERROR: Failed to create toolchain.
> THG:contrib thehe$ 
> ```

I build this in WSL. When I use code './compile-ffmpeg.sh all', I got the same error with you, but I changed code to './compile-ffmpeg.sh arm64', all works well. It seems can't compile with parameter 'arm'

**Comment by jianli-yang** [comment]
MacOs，本身就有python2.7，ERROR: Failed to create toolchain. 报错
```
build on Darwin x86_64
ANDROID_NDK=/Users/yangjianli/Library/Android/sdk/ndk-bundle
IJK_NDK_REL=21.0.6113669
NDKr21.0.6113669 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=8
BUILD_NUM_CPUS=16
Auto-config: --arch=arm
ERROR: Failed to create toolchain.
```

**Comment by befovy** [comment]
@jianli-yang  你用 NDK 21 版本，不支持。
换成 12 或 13 编译

**Comment by jianli-yang** [comment]
> @jianli-yang 你用 NDK 21 版本，不支持。
> 换成 12 或 13 编译

搞定了，我查了一下tools/do-compile-ffmpeg.s：43行给定的android api版本是9,我升级到21之后，
Library/Android/sdk/ndk-bundle/build/tools/make-standalone-toolchain.sh 中会调用
Library/Android/sdk/ndk-bundle/build/tools/make-standalone-toolchain.py，这个内部限定了最低版本要在16,所以引发的崩溃，我现在修改了43行为FF_ANDROID_PLATFORM=android-16,就可以了。
