### ISSUE TITLE
compiling ffmpeg ，armv7a is success，but x86 occur some error

### ISSUE THREAD

**Issue by mrldc** [Bilibili/ijkplayer#394]
after run ./compile-ffmpeg.sh all
====================
[*] check env armv7a
====================
build on CYGWIN_NT-6.1-WOW64 i686
ANDROID_SDK=E:/android_sdk_20G
ANDROID_NDK=E:/software/android-ndk-r9d
NDKr9d (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
Cygwin temp prefix=E:/software/cygwin/tmp/

--------------------
[*] checlibavcodec/libavcodec.a
INSTALL-libswresample/libswresample.a
INSTALL libswscale/libswscale.a
INSTALL-libavutil/libavutil.a
INSTALLflibavformat/avformat.h
INSTALL-libavformat/avio.h
INSTALLolibavformat/version.h
INSTALL libavformat/avc.h
INSTALL-libavformat/libavformat.pc
INSTALLplibavcodec/avcodec.h
INSTALL-libavcodec/avfft.h
INSTALLglibavcodec/dv_profile.hayer-master/android/contrib/ffmpeg-armv7a
INSTALLFlibavcodec/d3d11va.h
INSTALL libavcodec/dxva2.hormat.a
INSTALL libavcodec/old_codec_ids.h
INSTALL libavcodec/qsv.h
INSTALL libavcodec/vaapi.h
INSTALL libavcodec/vda.h
INSTALL libavcodec/vdpau.h
INSTALL libavcodec/version.h
INSTALL libavcodec/vorbis_parser.h
INSTALL libavcodec/xvmc.h
INSTALL libavcodec/libavcodec.pc
INSTALL libswresample/swresample.h
INSTALL libswresample/version.h
INSTALL libswresample/libswresample.pc
INSTALL libswscale/swscale.h
INSTALL libswscale/version.h
INSTALL libswscale/libswscale.pc
INSTALL libavutil/adler32.h
INSTALL libavutil/aes.h
INSTALL libavutil/attributes.h
INSTALL libavutil/audio_fifo.h
INSTALL libavutil/audioconvert.h
INSTALL libavutil/avassert.h
INSTALL libavutil/avstring.h
INSTALL libavutil/avutil.h
INSTALL libavutil/base64.h
INSTALL libavutil/blowfish.h
INSTALL libavutil/bprint.h
INSTALL libavutil/bswap.h
INSTALL libavutil/buffer.h
INSTALL libavutil/cast5.h
INSTALL libavutil/camellia.h
INSTALL libavutil/channel_layout.h
INSTALL libavutil/common.h
INSTALL libavutil/cpu.h
INSTALL libavutil/crc.h
INSTALL libavutil/display.h
INSTALL libavutil/downmix_info.h
INSTALL libavutil/error.h
INSTALL libavutil/eval.h
INSTALL libavutil/fifo.h
INSTALL libavutil/file.h
INSTALL libavutil/frame.h
INSTALL libavutil/hash.h
INSTALL libavutil/hmac.h
INSTALL libavutil/imgutils.h
INSTALL libavutil/intfloat.h
INSTALL libavutil/intreadwrite.h
INSTALL libavutil/lfg.h
INSTALL libavutil/log.h
INSTALL libavutil/macros.h
INSTALL libavutil/mathematics.h
INSTALL libavutil/md5.h
INSTALL libavutil/mem.h
INSTALL libavutil/motion_vector.h
INSTALL libavutil/murmur3.h
INSTALL libavutil/dict.h
INSTALL libavutil/old_pix_fmts.h
INSTALL libavutil/opt.h
INSTALL libavutil/parseutils.h
INSTALL libavutil/pixdesc.h
INSTALL libavutil/pixelutils.h
INSTALL libavutil/pixfmt.h
INSTALL libavutil/random_seed.h
INSTALL libavutil/replaygain.h
INSTALL libavutil/rational.h
INSTALL libavutil/ripemd.h
INSTALL libavutil/samplefmt.h
INSTALL libavutil/sha.h
INSTALL libavutil/sha512.h
INSTALL libavutil/stereo3d.h
INSTALL libavutil/threadmessage.h
INSTALL libavutil/time.h
INSTALL libavutil/timecode.h
INSTALL libavutil/timestamp.h
INSTALL libavutil/twofish.h
INSTALL libavutil/version.h
INSTALL libavutil/xtea.h
INSTALL libavutil/lzo.h
INSTALL libavutil/avconfig.h
INSTALL libavutil/ffversion.h
INSTALL libavutil/libavutil.pc

--------------------
[*] link ffmpeg
--------------------
-Wl,--fix-cortex-a8

--------------------
[*] create files for shared ffmpeg
--------------------
====================
[*] check env x86
====================
build on CYGWIN_NT-6.1-WOW64 i686
ANDROID_SDK=E:/android_sdk_20G
ANDROID_NDK=E:/software/android-ndk-r9d
NDKr9d (64-bit) detected

--------------------
[*] make NDK standalone toolchain
--------------------
Cygwin temp prefix=E:/software/cygwin/tmp/

--------------------
[*] check ffmpeg env
--------------------

--------------------
[*] configurate ffmpeg
--------------------
reuse configure

--------------------
[*] compile ffmpeg
--------------------
pwd:/cygdrive/e/ijkplayer/ijkplayer-master/android/contrib/ffmpeg-x86
FF_MAKEFLAGS:-j4
CC      libavcodec/x86/mpegvideoenc.o
CC      libavcodec/x86/rv34dsp_init.o
CC      libavcodec/x86/rv40dsp_init.o
YASM    libavcodec/x86/rv40dsp.o
STRIP   libavcodec/x86/rv40dsp.o
YASM    libavcodec/x86/sbrdsp.o
CC      libavcodec/x86/sbrdsp_init.o
STRIP   libavcodec/x86/sbrdsp.o
CC      libavcodec/x86/simple_idct.o
CC      libavcodec/x86/snowdsp.o
In file included from libavcodec/x86/mpegvideoenc.c:83:0:
libavcodec/x86/mpegvideoenc_template.c: In function 'dct_quantize_ssse3':
libavcodec/x86/mpegvideoenc_template.c:151:9: error: 'asm' operand has impossibl
e constraints
         __asm__ volatile(
         ^
libavcodec/x86/mpegvideoenc_template.c:186:9: error: 'asm' operand has impossibl
e constraints
         __asm__ volatile(
         ^
make: *** [libavcodec/x86/mpegvideoenc.o] Error 1
make: *** Waiting for unfinished jobs....
YASM    libavcodec/x86/ttadsp.o
STRIP   libavcodec/x86/ttadsp.o

----
I use cygwin to compile,whether it is i didn't install YASM?

**Comment by bbcallen** [comment]
Maybe an ffmpeg issue.

**Comment by xiaoyaomeng** [comment]
Your yasm version issue. 
http://blog.csdn.net/ljphhj/article/details/47421413

**Comment by bbcallen** [comment]
Reopen, if you have any more problem on this issue.
